### PR TITLE
Add travis and lint

### LINKED ISSUE #38: Travis
Currently the build always fails, this project needs a travis config.

### PR DESCRIPTION
**Pull request by frederickfogerty**
Closes #38

### CODE REVIEW

**Comment by frederickfogerty** [comment]
@souporserious please check the file changes and functionality to make sure you're happy. I tried not to touch too much to make the lint pass

**Comment by souporserious** [comment]
@frederickfogerty this is awesome! Thank you for taking care of that :)

**Comment by souporserious** [comment]
Thanks for your work on this, unfortunately it broke some things so I had to revert the PR. I'm going to deal with Travis later, I disabled it for now so it doesn't cause any problems. My bad for not pulling and running the code to make sure it worked.

**Comment by frederickfogerty** [comment]
Yeah sorry about that dude...

**Pull request merged**
